### ISSUE TITLE
I got problem with tabindex

### ISSUE THREAD

**Issue by Sam-Le68** [Sam-Le68/basic-accessibility#1]
![Screen Shot 2020-04-07 at 9 28 32 PM](https://user-images.githubusercontent.com/55094125/78681429-e9faf180-7916-11ea-8be9-11faba1b4a3c.png)

I followed every step of the lesson but Markbot said I might miss something but I don't know why.

@muxlowc
@mackenzierose

**Comment by MacKenzieRose** [comment]
Hi,

This error is being produced because you have a `href="#main"` link in your skip links, but no matching `id` or `tabindex` for the main section of your site. If you add those, you should be good to go.

Cheers! 
MacKenzie

**Comment by Sam-Le68** [comment]
Thank you so much
